"""initial

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_call",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_estimate", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("github_login", sa.String(length=100), nullable=False),
        sa.Column("teams_user_id", sa.String(length=200), nullable=True),
        sa.Column("whatsapp_number", sa.String(length=32), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_login"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("github_project_id", sa.String(length=100), nullable=True),
        sa.Column("team_channel_ref", sa.String(length=200), nullable=True),
        sa.Column("sprint_length_days", sa.Integer(), nullable=False),
        sa.Column("working_hours", sa.String(length=50), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_type"), "event", ["type"], unique=False)
    op.create_table(
        "nudge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("issue_node_id", sa.String(length=100), nullable=False),
        sa.Column("rule", sa.String(length=50), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nudge_issue_node_id"), "nudge", ["issue_node_id"], unique=False)
    op.create_index(op.f("ix_nudge_member_id"), "nudge", ["member_id"], unique=False)
    op.create_index(op.f("ix_nudge_project_id"), "nudge", ["project_id"], unique=False)
    op.create_table(
        "sprint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sprint_project_id"), "sprint", ["project_id"], unique=False)
    op.create_table(
        "escalation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nudge_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["nudge_id"],
            ["nudge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_escalation_nudge_id"), "escalation", ["nudge_id"], unique=False)
    op.create_table(
        "work_item_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("issue_node_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=100), nullable=True),
        sa.Column("assignee_login", sa.String(length=100), nullable=True),
        sa.Column("estimate", sa.Float(), nullable=True),
        sa.Column("sprint_id", sa.Integer(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sprint_id"],
            ["sprint.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_item_snapshot_issue_node_id"),
        "work_item_snapshot",
        ["issue_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_item_snapshot_project_id"), "work_item_snapshot", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_item_snapshot_project_id"), table_name="work_item_snapshot")
    op.drop_index(op.f("ix_work_item_snapshot_issue_node_id"), table_name="work_item_snapshot")
    op.drop_table("work_item_snapshot")
    op.drop_index(op.f("ix_escalation_nudge_id"), table_name="escalation")
    op.drop_table("escalation")
    op.drop_index(op.f("ix_sprint_project_id"), table_name="sprint")
    op.drop_table("sprint")
    op.drop_index(op.f("ix_nudge_project_id"), table_name="nudge")
    op.drop_index(op.f("ix_nudge_member_id"), table_name="nudge")
    op.drop_index(op.f("ix_nudge_issue_node_id"), table_name="nudge")
    op.drop_table("nudge")
    op.drop_index(op.f("ix_event_type"), table_name="event")
    op.drop_table("event")
    op.drop_table("project")
    op.drop_table("outbox")
    op.drop_table("member")
    op.drop_table("llm_call")
    # ### end Alembic commands ###
