"""outbox_dead_letters

Revision ID: 0006
Revises: 0005
"""

import sqlalchemy as sa
from alembic import op


revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("outbox", sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("outbox", sa.Column("dead_alerted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("outbox", sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox", "dismissed_at")
    op.drop_column("outbox", "dead_alerted_at")
    op.drop_column("outbox", "next_attempt_at")
    # ### end Alembic commands ###
